### ISSUE TITLE
Bit simpler Actions config

### ISSUE THREAD

**Issue by wipe2238** [cvet/fonline#57]
Not sure if it's useful for you or not, but building config can be simplified further to something like this:
```yml
# ... #
 build:
  runs-on: ${{ matrix.config.os }}
  strategy:
   matrix:
    config:
    - { os: windows-2019, script: "BuildScripts\\windows-win32.bat", artifact: binaries-windows-win32 }
    - { os: windows-2019, script: "BuildScripts\\windows-win64.bat", artifact: binaries-windows-win64 }
    - { os: ubuntu-18.04, script: "BuildScripts/linux.sh",           artifact: binaries-linux }
    - { os: ubuntu-18.04, script: "BuildScripts/android-arm32.sh",   artifact: binaries-android-arm32 }
    - { os: ubuntu-18.04, script: "BuildScripts/android-arm64.sh",   artifact: binaries-android-arm64 }
    - { os: ubuntu-18.04, script: "BuildScripts/web-release.sh",     artifact: binaries-web-release }
    - { os: ubuntu-18.04, script: "BuildScripts/web-debug.sh",       artifact: binaries-web-debug }
    - { os: macOS-10.14,  script: "BuildScripts/mac.sh",             artifact: binaries-mac }
    - { os: macOS-10.14,  script: "BuildScripts/ios.sh",             artifact: binaries-ios }
  steps:
  - uses: actions/checkout@v1
    with:
     fetch-depth: 1
  - name: Run build script
    run: ${{ matrix.config.script }}
  - uses: actions/upload-artifact@master
    with:
     name: ${{ matrix.config.artifact }}
     path: Build/Binaries
  - name: Upload FOnlineVersion.txt
    uses: actions/upload-artifact@master
    with:
     name: sdk-version
     path: Build/FOnlineVersion.txt
    if: matrix.config.artifact == 'binaries-windows-win32'
# ... #
```
It keeps current logic (unless i missed something), with uploading `sdk-version` only once. Everything after and including `unit-tests` job should be as it is now, except parts which needs dependency:
```yml
  make:
   needs: [build, unit-tests, code-coverage]
```

Didn't test it _fully_, but if `run: ${{ matrix.config.script }}` step works properly, everything else should.

There's one small disadvantage - checks names won't be as "clean" as they are now ;)
![image](https://user-images.githubusercontent.com/1433300/65298288-3b09ea80-db6b-11e9-950c-7919172702a9.png)
